# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 511f69112e9155c4cfeecd12020299d93694a3f7b49f784324c0e5900c3cd3d67fe70d0d63b4c3018ff3020b2bf5533a22be11d2ba34abaed1aeeccd70d3419f

test:
  secret_key_base: 8470dc4b8ed7cf39a51a4a7230b7a5bbb61b3d964215e202757deb982e178ca146135141203e49fdf05b7f2387f5b1d355dee25cd423ca83b88365d286148c79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
